spirit_buzz_project/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'spirit_buzz_project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^spiritbuzz/', include('spiritbuzz.urls')),
)

spiritbuzz/urls.py
from django.conf.urls import patterns, url
from spiritbuzz import views
from spirit_buzz_project import settings

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^category/(?P<category_slug>[-\w]+)/$', views.category, name='category'),
    url(r'^category/(?P<category_slug>[-\w]+)/product/(?P<product_slug>[-\w]+)/$', views.product, name ='product'),
    url(r'^login/', views.user_login, name = 'login'),
    url(r'^register/$', views.register, name='register'),
    url(r'^aboutus/', views.aboutus, name = 'aboutus'),
    url(r'^cart/$', views.show_cart, name = 'show_cart'),
    url(r'^checkout/$', views.show_checkout, {'template_name': 'spiritbuzz/checkout.html', 'SSL' : settings.ENABLE_SSL}, name = 'show_checkout'),
    url(r'^receipt/$', views.receipt, {'template_name': 'spiritbuzz/receipt.html', 'SSL': settings.ENABLE_SSL}, name = 'checkout_receipt'),
    url(r'^results/$', views.results, {'template_name': 'spiritbuzz/results.html'}, name = 'search_results'),
    url(r'^review/product/add/$','add_review'),
    )

spiritbuzz/models.py
from django.db import models
# Import the Category model
from django.contrib.auth.models import User
import decimal

class ActiveCategoryManager(models.Manager):
    def get_query_set(self):
        return super(ActiveCategoryManager, self).get_query_set().filter(is_active = True)

class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    slug = models.SlugField(max_length = 50, unique = True, help_text = 'Unique value for category page URL, created from name.')
    description = models.TextField()
    is_active = models.BooleanField(default = True)
    meta_keywords = models.CharField('Meta Keywords', max_length = 255, help_text = 'Comma delimited set of SEO keywords for meta tag')
    meta_description = models.CharField('Meta Description', max_length = 255, help_text = 'Content for description meta Tag')
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    objects = models.Manager()
    active = ActiveCategoryManager()

    class Meta:
        db_table = 'categories'
        ordering = ['-created_at']
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

@models.permalink
def get_absolute_url(self):
    return ('category', (), {'category_slug': self.slug})

class ActiveProductManager(models.Manager):
    def get_query_set(self):
        return super(ActiveProductManager, self).get_query_set().filter(is_active = True)

class FeaturedProductManager(models.Manager):
    def all(self):
        return super(FeaturedProductManager, self).all().filter(is_active = True).filter(is_featured = True)


class Product(models.Model):
    category = models.ForeignKey(Category)
    name = models.CharField(max_length=128, unique = True)
    slug = models.SlugField(max_length = 128, unique = True, help_text = 'Unique value for product page url, created from name.')
    sku = models.CharField(max_length = 50, unique = True)
    description = models.TextField()
    size = models.IntegerField(default = 750)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    old_price = models.DecimalField(max_digits=7, decimal_places=2, blank = True, default = 0.00)
    picture = models.ImageField(upload_to='products', blank=True)
    is_active = models.BooleanField(default = True)
    is_featured = models.BooleanField(default = True)
    meta_keywords = models.CharField('Meta Keywords', max_length = 255, help_text = 'Comma delimited set of SEO keywords for meta tag')
    meta_description = models.CharField('Meta Description', max_length = 255, help_text = 'Content for description meta Tag')
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    views = models.IntegerField(default=0)
    objects = models.Manager()
    active = ActiveProductManager()
    featured = FeaturedProductManager()

    class Meta:
        db_table = 'products'
        ordering = ['-created_at']

    def __str__(self):
        return self.name

    @models.permalink
    def get_absolute_url(self):
        return ('product', (), {'product_slug': self.slug})

    @property
    def sale_price(self):
        if self.old_price > self.price:
            return self.price
        else:
            return None

    def cross_sells_hybrid(self):

        from spiritbuzz.models import Order, OrderItem
        from django.contrib.auth.models import User
        from django.db.models import Q

        orders = Order.objects.filter(orderitem__product = self)
        users = User.objects.filter(order__orderitem__product = self)
        items = OrderItem.objects.filter(Q(order__user__in = users)).exclude(product = self)
        products = Product.active.filter(orderitem__in = items).distinct()

        return products

class UserProfile(models.Model):
    # This line is required. Links UserProfile to a User model instance.
    user = models.OneToOneField(User)

    # The additional attributes we wish to include.
    #isAdmin = models.BooleanField()
    picture = models.ImageField(upload_to='profile_images', blank=True)

    # Override the __unicode__() method to return out something meaningful!
    def __str__(self):
        return self.user.username

class CartItem(models.Model):
    cart_id = models.CharField(max_length = 50)
    date_added = models.DateTimeField(auto_now_add = True)
    quantity = models.IntegerField(default = 1)
    product = models.ForeignKey('spiritbuzz.Product', unique = False)

    class Meta:
        db_table = 'cart_items'
        ordering = ['date_added']

    @property
    def total(self):
        return self.quantity * self.product.price

    @property
    def name(self):
        return self.product.name

    @property
    def price(self):
        return self.product.price

    def get_absolute_url(self):
        return self.product.get_absolute_url()

    def augment_quantity(self, quantity):
        self.quantity = self.quantity + int(quantity)
        self.save()

class Order(models.Model):

    SUBMITTED = 1
    PROCESSED = 2
    SHIPPED = 3
    CANCELLED = 4

    ORDER_STATUSES = ((SUBMITTED, 'Submitted'),(PROCESSED, 'Processed'),(SHIPPED, 'Shipped'),(CANCELLED, 'Cancelled'),)

    date = models.DateTimeField(auto_now_add = True)
    status = models.IntegerField(choices = ORDER_STATUSES, default = SUBMITTED)
    ip_address = models.IPAddressField()
    last_updated = models.DateTimeField(auto_now = True)
    user = models.ForeignKey(User, null = True)
    transaction_id = models.CharField(max_length = 20)

    email = models.EmailField(max_length = 50)
    phone = models.CharField(max_length = 20)

    shipping_name = models.CharField(max_length = 50)
    shipping_address_1 = models.CharField(max_length = 50)
    shipping_address_2 = models.CharField(max_length = 50, blank = True)
    shipping_city = models.CharField(max_length = 50)
    shipping_state = models.CharField(max_length = 2)
    shipping_country = models.CharField(max_length = 50)
    shipping_zip = models.CharField(max_length = 10)

    billing_name = models.CharField(max_length = 50)
    billing_address_1 = models.CharField(max_length = 50)
    billing_address_2 = models.CharField(max_length = 50, blank = True)
    billing_city = models.CharField(max_length = 50)
    billing_state = models.CharField(max_length = 2)
    billing_country = models.CharField(max_length = 50)
    billing_zip = models.CharField(max_length = 10)

    def __str__(self):
        return 'Order #:' + str(self.id)

    @property
    def total(self):
        total = decimal.Decimal('0.00')
        order_items = OrderItem.objects.filter(order = self)

        for item in order_items:
            total += item.total

        return total

class OrderItem(models.Model):

    product = models.ForeignKey(Product)
    quantity = models.IntegerField(default = 1)
    price = models.DecimalField(max_digits = 9, decimal_places = 2)
    order = models.ForeignKey(Order)

    @property
    def total(self):
        return self.quantity * self.price

    @property
    def name(self):
        return self.product.name

    @property
    def sku(self):
        return self.product.sku

    def __str__(self):
        return self.product.name + '(' + self.product.sku + ')'

class SearchTerm(models.Model):

    q = models.CharField(max_length = 50)
    search_date = models.DateTimeField(auto_now_add = True)
    ip_address = models.IPAddressField()
    user = models.ForeignKey(User, null = True)
    tracking_id = models.CharField(max_length = 50, default = '')

    def __str__(self):
        return self.q

class PageView(models.Model):

    class Meta:
        abstract = True

    date = models.DateTimeField(auto_now = True)
    ip_address = models.IPAddressField()
    user = models.ForeignKey(User, null = True)
    tracking_id = models.CharField(max_length = 50, default = '')

class ProductView(PageView):
    product = models.ForeignKey(Product)

class ActiveProductReviewManager(models.Manager):

    def all(self):
        return super(ActiveProductReviewManager, self).all().filter(is_approved = True)

class ProductReview(models.Model):

    RATINGS = [(5,5),(4,4),(3,3),(2,2),(1,1),]
    product = models.ForeignKey(Product)
    user = models.ForeignKey(User)
    title = models.CharField(max_length = 50)
    date = models.DateTimeField(auto_now_add = True)
    rating = models.PositiveSmallIntegerField(default = 5, choices = RATINGS)
    is_approved = models.BooleanField(default = True)
    content = models.TextField()
    objects = models.Manager()
    approved = ActiveProductReviewManager()

spiritbuzz/forms.py
from django import forms
from spiritbuzz.models import Product, Category, UserProfile, Order, SearchTerm, ProductReview
from django.contrib.auth.models import User
import datetime
import re



class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text="Please enter the category name.")
    #views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    #likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    # An inline class to provide additional information on the form.
    class Meta:
        # Provide an association between the ModelForm and a model
        model = Category

class ProductForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text="Please enter the name of the product.")
    description = forms.CharField(max_length=1000, help_text="Please enter a description.")
    size = forms.IntegerField()
    price = forms.DecimalField(help_text = "Please enter sale price:")
    picture = forms.ImageField()


    class Meta:
        # Provide an association between the ModelForm and a model
        model = Product

        # What fields do we want to include in our form?
        # This way we don't need every field in the model present.
        # Some fields may allow NULL values, so we may not want to include them...
        # Here, we are hiding the foreign key.
        fields = ('name','description', 'size', 'price', 'picture')

class UserForm(forms.ModelForm):
    password = forms.CharField(label = "Password", widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('picture',)

class ProductAdminForm(forms.ModelForm):
    class Meta:
        model = Product

    def clean_price(self):
        if self.cleaned_data['price'] <= 0:
            raise forms.ValidationError('Price must be greater than 0.')

        return self.cleaned_data['price']

class ProductAddToCartForm(forms.Form):
    #quantity = forms.IntegerField(widget = forms.TextInput(attrs = {'size': '2', 'value': '1', 'class': 'quantity', 'maxlength': '5'}), error_messages = {'invalid': 'Please enter a valid quantity.'}, min_value = 1)
    product_slug = forms.CharField(widget = forms.HiddenInput())

    def __init__(self, request = None, *args, **kwargs):
        self.request = request
        super(ProductAddToCartForm, self).__init__(*args, **kwargs)

    def clean(self):
        if self.request:
            if not self.request.session.test_cookie_worked():
                raise forms.ValidationError("Cookies must be enabled.")

        return self.cleaned_data

def cc_expire_years():

    current_year = datetime.datetime.now().year
    years = range(current_year, current_year + 12)

    return [(str(x), str(x)) for x in years]

def cc_expire_months():

    months = []

    for month  in range(1, 13):
        if len(str(month)) == 1:
            numeric = '0' + str(month)
        else:
            numeric = str(month)

        months. append((numeric, datetime.date(2014, month, 1).strftime('%B')))

    return months

CARD_TYPES = (('Mastercard', 'Mastercard'), ('VISA', 'VISA'), ('AMEX', 'AMEX'), ('Discover', 'Discover'),)

STATE_ABBREVS =(( 'AL','AL'),('AK','AK'),('AZ','AZ'),('AR','AR'),('CA','CA'),('CO','CO'),('CT','CT'),('DE','DE'),('FL','FL'),('GA','GA'),('HI','HI'),('ID','ID'),('IL','IL'),('IN','IN'),('IA','IA'),('KS','KS'),('KY','KY'),('LA','LA'),('ME','ME'),('MD','MD'),('MA','MA'),('MI','MI'),('MN','MN'),('MS','MS'),('MO','MO'),('MT','MT'),('NE','NE'),('NV','NV'),('NH','NH'),('NJ','NJ'),('NM','NM'),('NY','NY'),('NC','NC'),('ND','ND'),('OH','OH'),('OK','OK'),('OR','OR'),('PA','PA'),('RI','RI'),('SC','SC'),('SD','SD'),('TN','TN'),('TX','TX'),('UT','UT'),('VT','VT'),('VA','VA'),('WA','WA'),('WV','WV'),('WI','WI'),('WY','WY'),)

def strip_non_numbers(data):

    non_numbers = re.compile('\D')

    return non_numbers.sub('', data)

def cardLuhnChecksumIsValid(card_number):

    sum = 0
    num_digits = len(card_number)
    oddeven = num_digits & 1

    for count in range(0, num_digits):
        digit = int(card_number[count])
        if not ((count & 1) ^ oddeven):
            digit = digit * 2
        if digit > 9:
            digit = digit - 9
        sum = sum + digit

    return ((sum % 10) == 0)

class CheckoutForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):

        super(CheckoutForm, self).__init__(*args, **kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs['size'] = '30'

        #self.fields['shipping_state'].widget.attrs['size'] = '3'
        self.fields['shipping_state'].widget.attrs['size'] = '1'
        self.fields['shipping_zip'].widget.attrs['size'] = '6'
        #self.fields['billing_state'].widget.attrs['size'] = '3'
        self.fields['billing_state'].widget.attrs['size'] = '1'
        self.fields['billing_zip'].widget.attrs['size'] = '6'
        self.fields['credit_card_type'].widget.attrs['size'] = '1'
        self.fields['credit_card_expire_year'].widget.attrs['size'] = '1'
        self.fields['credit_card_expire_month'].widget.attrs['size'] = '1'
        self.fields['credit_card_cvv'].widget.attrs['size'] = '5'

    class Meta:
        model = Order
        exclude = ('satus', 'ip_address', 'user', 'transaction_id',)
    shipping_state = forms.CharField(widget = forms.Select(choices = STATE_ABBREVS))
    billing_state = forms.CharField(widget = forms.Select(choices = STATE_ABBREVS))
    credit_card_number = forms.CharField()
    credit_card_type = forms.CharField(widget = forms.Select(choices = CARD_TYPES))
    credit_card_expire_year = forms.CharField(widget = forms.Select(choices = cc_expire_years()))
    credit_card_expire_month = forms.CharField(widget = forms.Select(choices = cc_expire_months()))

    credit_card_cvv = forms.CharField()

def clean_credit_card_number(self):

    cc_number = self.cleaned_data['credit_card_number']
    stripped_cc_number = strip_non_numbers(cc_number)

    if not cardLuhnChecksumIsValid(stripped_cc_number):
        raise forms.ValidationError('The credit card you entered is invalid.')

def clean_phone(self):

    phone = self.cleaned_data['phone']
    stripped_phone = strip_non_numbers(phone)

    if len(stripped_phone) < 10:
        raise forms.ValidationError('Enter a valid phone number with area code. (e.g. 555-555-5555)')

    return self.cleaned_data['phone']

class SearchForm(forms.ModelForm):

    class Meta:
        model = SearchTerm

    def __init__(self, *args, **kwargs):
        super(SearchForm, self).__init__(*args, **kwargs)
        default_text = ''
        self.fields['q'].widget.attrs['value'] = default_text
        self.fields['q'].widget.attrs['onfocus'] = "if (this.value =='"+default_text+"')this.value = ''"

    include = ('q',)

class ProductReviewForm(forms.ModelForm):

    class Meta:
        model = ProductReview
        exclude = ('user', 'product', 'is_approved')

templates/spiritbuzz/checkout.html
{% load static %}
{% include 'tags/navigation.html' %}


        <div id="content">
        <div class="container">
        <div id="shoppingcartline">CHECKOUT!</div>


        <div id="checkoutform">

        <form action = "." method = "post"> <input type='hidden' name='csrfmiddlewaretoken' value='uqROITloVqCF14vxPph3y4NJ3gTZQRBM' />
         <div id="chckoutleft">
        <fieldset class = "Checkout">
        <legend>Contact Info</legend>

        <table>
        <tr>
        <th>
        <label for="id_email">EMAIL</label>
        </th>

        <td>
        <input id="id_email" maxlength="50" name="email" size="30" type="email" />
        </td>
        </tr>

        <tr>
        <th>

        <label for="id_phone">PHONE</label>
        </th>

        <td>
        <input id="id_phone" maxlength="20" name="phone" size="30" type="text" />
        </td>
        </tr>
        </table>
        </fieldset>

        <fieldset class = "Checkout">
        <legend>SHIPPING INFO</legend>
        <table>
        <tr>
        <th>

        <label for="id_shipping_name">Shipping name</label>
        </th>
        <td>

        <input id="id_shipping_name" maxlength="50" name="shipping_name" size="30" type="text" />
        </td>
        </tr>

        <tr>
        <th>

        <label for="id_shipping_address_1">Shipping address 1</label>
        </th>
        <td>

        <input id="id_shipping_address_1" maxlength="50" name="shipping_address_1" size="30" type="text" />
        </td>
        </tr>

        <tr>
        <th>

        <label for="id_shipping_address_2">Shipping address 2</label>
        </th>
        <td>

        <input id="id_shipping_address_2" maxlength="50" name="shipping_address_2" size="30" type="text" />
        </td>
        </tr>

        <tr>
        <th>
        <label for="id_shipping_city">SHIPPING CITY</label>
        </th>
        <td>
        <input id="id_shipping_city" maxlength="50" name="shipping_city" size="30" type="text" />
        </td>
        </tr>

        <tr>
        <th>
        <label for="id_shipping_state">SHIPPING STATE</label>
        </th>

        <td>

        <select id="id_shipping_state" name="shipping_state" size="1">
        <option value="AL">AL</option>
        <option value="AK">AK</option>
        <option value="AZ">AZ</option>
        <option value="AR">AR</option>
        <option value="CA">CA</option>
        <option value="CO">CO</option>
        <option value="CT">CT</option>
        <option value="DE">DE</option>
        <option value="FL">FL</option>
        <option value="GA">GA</option>
        <option value="HI">HI</option>
        <option value="ID">ID</option>
        <option value="IL">IL</option>
        <option value="IN">IN</option>
        <option value="IA">IA</option>
        <option value="KS">KS</option>
        <option value="KY">KY</option>
        <option value="LA">LA</option>
        <option value="ME">ME</option>
        <option value="MD">MD</option>
        <option value="MA">MA</option>
        <option value="MI">MI</option>
        <option value="MN">MN</option>
        <option value="MS">MS</option>
        <option value="MO">MO</option>
        <option value="MT">MT</option>
        <option value="NE">NE</option>
        <option value="NV">NV</option>
        <option value="NH">NH</option>
        <option value="NJ">NJ</option>
        <option value="NM">NM</option>
        <option value="NY">NY</option>
        <option value="NC">NC</option>
        <option value="ND">ND</option>
        <option value="OH">OH</option>
        <option value="OK">OK</option>
        <option value="OR">OR</option>
        <option value="PA">PA</option>
        <option value="RI">RI</option>
        <option value="SC">SC</option>
        <option value="SD">SD</option>
        <option value="TN">TN</option>
        <option value="TX">TX</option>
        <option value="UT">UT</option>
        <option value="VT">VT</option>
        <option value="VA">VA</option>
        <option value="WA">WA</option>
        <option value="WV">WV</option>
        <option value="WI">WI</option>
        <option value="WY">WY</option>
        </select>
        </td>
        </tr>

        <tr>
        <th>
        <label for="id_shipping_zip">SHIPPING ZIP</label>
        </th>
        <td>

        <input id="id_shipping_zip" maxlength="10" name="shipping_zip" size="6" type="text" />
        </td>
        </tr>

        </table>
        </fieldset>
        </div>


    <div id="chckoutright">
        <fieldset class = "Checkout">

        <legend>BILLING INFO</legend>
        <table>
        <tr>
        <th>
        <label for="id_billing_name">BILLING NAME</label>
        </th>
        <td>

        <input id="id_billing_name" maxlength="50" name="billing_name" size="30" type="text" />
        </td>
        </tr>

        <tr>
        <th>
        <label for="id_billing_address_1">Billing address 1</label>
        </th>
        <td>

        <input id="id_billing_address_1" maxlength="50" name="billing_address_1" size="30" type="text" />
        </td>
        </tr>

        <tr>
        <th>
        <label for="id_billing_address_2">Billing address 2</label>
        </th>

        <td>
        <input id="id_billing_address_2" maxlength="50" name="billing_address_2" size="30" type="text" />
        </td>
        </tr>

        <tr>
        <th>
        <label for="id_billing_city">Billing city</label>
        </th>

        <td>
        <input id="id_billing_city" maxlength="50" name="billing_city" size="30" type="text" />
        </td>
        </tr>

        <tr>
        <th>
        <label for="id_billing_state">Billing state</label>
        </th>

        <td>
        <select id="id_billing_state" name="billing_state" size="1">
        <option value="AL">AL</option>
        <option value="AK">AK</option>
        <option value="AZ">AZ</option>
        <option value="AR">AR</option>
        <option value="CA">CA</option>
        <option value="CO">CO</option>
        <option value="CT">CT</option>
        <option value="DE">DE</option>
        <option value="FL">FL</option>
        <option value="GA">GA</option>
        <option value="HI">HI</option>
        <option value="ID">ID</option>
        <option value="IL">IL</option>
        <option value="IN">IN</option>
        <option value="IA">IA</option>
        <option value="KS">KS</option>
        <option value="KY">KY</option>
        <option value="LA">LA</option>
        <option value="ME">ME</option>
        <option value="MD">MD</option>
        <option value="MA">MA</option>
        <option value="MI">MI</option>
        <option value="MN">MN</option>
        <option value="MS">MS</option>
        <option value="MO">MO</option>
        <option value="MT">MT</option>
        <option value="NE">NE</option>
        <option value="NV">NV</option>
        <option value="NH">NH</option>
        <option value="NJ">NJ</option>
        <option value="NM">NM</option>
        <option value="NY">NY</option>
        <option value="NC">NC</option>
        <option value="ND">ND</option>
        <option value="OH">OH</option>
        <option value="OK">OK</option>
        <option value="OR">OR</option>
        <option value="PA">PA</option>
        <option value="RI">RI</option>
        <option value="SC">SC</option>
        <option value="SD">SD</option>
        <option value="TN">TN</option>
        <option value="TX">TX</option>
        <option value="UT">UT</option>
        <option value="VT">VT</option>
        <option value="VA">VA</option>
        <option value="WA">WA</option>
        <option value="WV">WV</option>
        <option value="WI">WI</option>
        <option value="WY">WY</option>
        </select>
        </td>
        </tr>

        <tr>
        <th>
        <label for="id_billing_zip">Billing zip</label>
        </th>

        <td>
        <input id="id_billing_zip" maxlength="10" name="billing_zip" size="6" type="text" />
        </td>
        </tr>

        <tr>
        <th>
        <label for="id_billing_country">Billing country</label>
        </th>

        <td>
        <input id="id_billing_country" maxlength="50" name="billing_country" size="30" type="text" />
        </td>
        </tr>
        </table>
        </fieldset>


        <fieldset class = "Checkout">
        <legend>Credit Card Info</legend>
        <table>
        <tr>
        <th>

        <label for="id_credit_card_number">Credit card number</label>
        </th>
        <td>

        <input id="id_credit_card_number" name="credit_card_number" size="30" type="text" />
        </td>
        </tr>
        <tr>
        <th>

        <label for="id_credit_card_type">Credit card type</label>
        </th>
        <td>

        <select id="id_credit_card_type" name="credit_card_type" size="1">
        <option value="Mastercard">Mastercard</option>
        <option value="VISA">VISA</option>
        <option value="AMEX">AMEX</option>
        <option value="Discover">Discover</option>
        </select>
        </td>
        </tr>
        <tr>
        <th>

        <label for="id_credit_card_expire_month">expiration month</label>
        </th>
        <td>

        <select id="id_credit_card_expire_month" name="credit_card_expire_month" size="1">
        <option value="01">January</option>
        <option value="02">February</option>
        <option value="03">March</option>
        <option value="04">April</option>
        <option value="05">May</option>
        <option value="06">June</option>
        <option value="07">July</option>
        <option value="08">August</option>
        <option value="09">September</option>
        <option value="10">October</option>
        <option value="11">November</option>
        <option value="12">December</option>
        </select>
        </td>
        </tr>
        <tr>
        <th>
        <label for="id_credit_card_expire_year">expiration year</label>
        </th>
        <td>

        <select id="id_credit_card_expire_year" name="credit_card_expire_year" size="1">
        <option value="2014">2014</option>
        <option value="2015">2015</option>
        <option value="2016">2016</option>
        <option value="2017">2017</option>
        <option value="2018">2018</option>
        <option value="2019">2019</option>
        <option value="2020">2020</option>
        <option value="2021">2021</option>
        <option value="2022">2022</option>
        <option value="2023">2023</option>
        <option value="2024">2024</option>
        <option value="2025">2025</option>
        </select>
        </td>
        </tr>

        <tr>
        <th>

        <label for="id_credit_card_cvv">Credit card cvv</label>
        </th>
        <td>

        <input id="id_credit_card_cvv" name="credit_card_cvv" size="5" type="text" />
        </td>
        </tr>
        </table>

        <table>
        <tr>
        <th colspan = "2">
        <input type = "submit" value = "Place Order" class = "submit"/>
        </th>
        </tr>
        </table>
        </form>
        </fieldset>
        </div>

        </div>
        </div>
        </div>

    	<div id="footer">
        SPIRITBUZZ ©2014
        </div>

        </body>
        </html>

templates/spiritbuzz/index.html
{% include 'tags/navigation.html' %}
{% load catalog_tags %}
{% block content %}
{% product_list recently_viewed 'Your Recently Viewed' %}<br/>
{% product_list view_recs 'Similar Products' %}<br/>
{% product_list featured 'Featured Products' %}<br/>

{% endblock %}


<body>








                <div id="mainimage">

                </div>


                <div id="footer">
                SPIRITBUZZ ©2014
                </div>
</div>

</body>
</html>

templates/spiritbuzz/register.html
{% load static %}
{% include 'tags/navigation.html' %}



                <div id="content" align="center">
                <div id="logintagline" align="center"> </div>

                {% if registered %}
                Thank you for registering!
                <a href="/spiritbuzz/">Return to the homepage.</a><br />
                {% else %}
                <br />

                <form id="user_form" method="post" action="/spiritbuzz/register/"
                enctype="multipart/form-data">

                {% csrf_token %}

            <!-- Display each form. The as_p method wraps each element in a paragraph
                 (<p>) element. This ensures each element appears on a new line,
                 making everything look neater. -->

Username<input type="id_username" maxlength="30" name="username" />
<p><span class="helptext">Required. 30 characters or fewer. Letters, numbers and @/./+/-/_ characters</span></p>

Email address<input id="id_email" maxlength="75" name="email" type="email" />
Password<input id="id_password" name="password" type="password" />



            <!-- Provide a button to click to submit the form. -->
            <input type="submit" name="submit" value="Register" />
            </form>
            {% endif %}
            </div>


        	<div id="footer">
            SPIRITBUZZ ©2014
            </div>

</body>
</html>